In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

Init Plugin
2.5.0
Init Graph Optimizer
Init Kernel


In [2]:
# Create tensors with tf.constant() may not be building my own tensors
scalar = tf.constant(7)
scalar


Metal device set to: Apple M1


2022-07-19 21:20:30.093390: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-07-19 21:20:30.093871: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of our vector
vector.ndim

1

In [6]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[10., 7.], [3., 2.], [8., 9.]], dtype=tf.float16) # specify the data type with dtype parameter.
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# What's the number of dimensions of another_matrix
another_matrix.ndim

2

In [10]:
# Let's create a tensor.
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]],
                       [[13, 14, 15],
                        [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
# ndim number of dimensions
tensor.ndim

3

What weve create so far:
* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

In [12]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [13]:
# Create the tensor with the tf.Variable() as above.
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# Let's try change one of the elements in our changeable tensor with .assign
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
# Let's try change unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
#Creating random tensors
# Random tensors are tensors of some abitray size which contain random numbers.

In [ ]:
# Create two random (but the same) tensors tensor.random.uniform
with tf.device('/cpu:0'): # Needed for Mac M1 due to incomparable with GPU
    random_1 = tf.random.Generator.from_seed(7) # set seed for reproducibility
    random_1 = random_1.normal(shape=(3,2))
    random_2 = tf.random.Generator.from_seed(7)
    random_2 = random_2.normal(shape=(3,2))
random_2

In [ ]:
# Are random 1 and 2 equal?
random_1, random_2, random_1 == random_2

In [ ]:
### Shuffle the order of elements in a tensor
# Shuffle a tensor (Why do you want to shuffle your data so that the inherent order doesn't make bias to one particular item.)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)


In [ ]:
not_shuffled

In [ ]:
tf.random.shuffle(not_shuffled, seed=42)

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

In [ ]:
# Exercise Read through tensor flow documentation on random seed generation:
# Shuffle our non-shuffled tensor
tf.random.set_seed(42) # Global random seed
tf.random.shuffle(not_shuffled, seed=42) # Operational random seed.
# To keep shuffled tensors the same need to set both the Global and operational seeds.
# This is to have reproducial experiements.  

In [ ]:
#Other ways to make tensors
# Create a tensor of all ones
tf.ones([10, 7])

In [ ]:
tf.zeros(shape=(3,4))

In [ ]:
# Turn numpy arrays into tensors
# The difference between numpy arrays and tensor, tensors can be ran on a GPU much faster.
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
numpy_A
# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

In [ ]:
A = tf.constant(numpy_A, shape=(3, 8)) # The shape has to multiple to the number of the original array
B = tf.constant(numpy_A)
A, B

In [ ]:
A.ndim, B.ndim, A[:1]

In [ ]:
# Getting information from tensors
# Shape, Rank, Axis or dimension, Size When dealing with Tensor you want to know the following attributes


In [ ]:
# Create a rank 4 tensor (4 dimensions)
# Passing tensors and tensor output has to be in a certain shape.
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)  #ndim = the number of elements in the TensorShape
# e.g. shape=(2,3,4,5) = ndim 4 or 4 elements in the tuple

In [ ]:
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements alont the last axis:", rank_4_tensor.shape[-1])
print("Total numbers of our tensor", tf.size(rank_4_tensor.numpy()))
print("Total numbers of our tensor", tf.size(rank_4_tensor))

In [ ]:
### Indexing tensors, tensors can be index just like python lists
# Get the first 2 elements of each dimension

In [ ]:
# Get the first two elements of each tensor
rank_4_tensor[:2, :2, :2, :2]

In [ ]:
# Get the first element of each dimension from each index except for the final one
rank_4_tensor[:1, :1, :, :1]

In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

In [ ]:
# Get the last item of each of our rank 2 tensor
rank_2_tensor[:, -1]

In [ ]:
# Alter Tensor to meet a certain shape add extra dimension
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

In [ ]:
# Alternative to tf.newaxis to add an extra dimensions
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" expand the final axis

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1)

In [17]:
### Manipulating Tensors
### You can add values to a tensor using the addition operator this will add 10 to each value
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor + 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [18]:
# Original Tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [19]:
# Multiplication operation this will multiply 
tensor * 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [20]:
# We can use the tensorflow to substract
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [21]:
# We can use the tensorflow built-in function too
# If I want the tensorflow operation sped up best to use to builtin utilities like below
tf.multiply(tensor, 10) # As oppose to tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [31]:
# Matrix Multiplication in machine learning, matrix multiplication 
# is one of the most common tensor operations
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [52]:
# Practice for 2:31:00 Homework
tensor1 = tf.constant([[1, 2], [1, 1], [3, 3]])
tensor2 = tf.constant([[4, 5], [6, 7]])

In [53]:
# For Homework above
tf.matmul(tensor1, tensor2)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[16, 19],
       [10, 12],
       [30, 36]], dtype=int32)>

In [49]:
# Matrix multiplication with python "@"
tensor1 @ tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[14, 19],
       [ 8, 12],
       [24, 36]], dtype=int32)>