In [1]:
# Import TensorFlow
import tensorflow as tf
# Import numpy as np
import numpy as np
# Import tensorflow_probability as tfp
import tensorflow_probability as tfp
print(tf.__version__)

Init Plugin
Init Graph Optimizer
Init Kernel
2.5.0


In [2]:
# Create tensors with tf.constant() may not be building my own tensors
scalar = tf.constant(7)
scalar


Metal device set to: Apple M1


2022-07-21 11:03:02.706625: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-07-21 11:03:02.706765: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of our vector
vector.ndim

1

In [6]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[10., 7.], [3., 2.], [8., 9.]], dtype=tf.float16) # specify the data type with dtype parameter.
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# What's the number of dimensions of another_matrix
another_matrix.ndim

2

In [10]:
# Let's create a tensor.
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [11]:
# ndim number of dimensions
tensor.ndim

2

What weve create so far:
* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

In [12]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [13]:
# Create the tensor with the tf.Variable() as above.
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# Let's try change one of the elements in our changeable tensor with .assign
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
# Let's try change unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
#Creating random tensors
# Random tensors are tensors of some abitray size which contain random numbers.

In [ ]:
# Create two random (but the same) tensors tensor.random.uniform
with tf.device('/cpu:0'): # Needed for Mac M1 due to incomparable with GPU
    random_1 = tf.random.Generator.from_seed(7) # set seed for reproducibility
    random_1 = random_1.normal(shape=(3,2))
    random_2 = tf.random.Generator.from_seed(7)
    random_2 = random_2.normal(shape=(3,2))
random_2

In [ ]:
# Are random 1 and 2 equal?
random_1, random_2, random_1 == random_2

In [ ]:
### Shuffle the order of elements in a tensor
# Shuffle a tensor (Why do you want to shuffle your data so that the inherent order doesn't make bias to one particular item.)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)


In [ ]:
not_shuffled

In [ ]:
tf.random.shuffle(not_shuffled, seed=42)

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

In [ ]:
# Exercise Read through tensor flow documentation on random seed generation:
# Shuffle our non-shuffled tensor
tf.random.set_seed(42) # Global random seed
tf.random.shuffle(not_shuffled, seed=42) # Operational random seed.
# To keep shuffled tensors the same need to set both the Global and operational seeds.
# This is to have reproducial experiements.  

In [ ]:
#Other ways to make tensors
# Create a tensor of all ones
tf.ones([10, 7])

In [ ]:
tf.zeros(shape=(3,4))

In [ ]:
# Turn numpy arrays into tensors
# The difference between numpy arrays and tensor, tensors can be ran on a GPU much faster.
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
numpy_A
# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

In [ ]:
A = tf.constant(numpy_A, shape=(3, 8)) # The shape has to multiple to the number of the original array
B = tf.constant(numpy_A)
A, B

In [ ]:
A.ndim, B.ndim, A[:1]

In [ ]:
# Getting information from tensors
# Shape, Rank, Axis or dimension, Size When dealing with Tensor you want to know the following attributes


In [ ]:
# Create a rank 4 tensor (4 dimensions)
# Passing tensors and tensor output has to be in a certain shape.
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)  #ndim = the number of elements in the TensorShape
# e.g. shape=(2,3,4,5) = ndim 4 or 4 elements in the tuple

In [ ]:
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements alont the last axis:", rank_4_tensor.shape[-1])
print("Total numbers of our tensor", tf.size(rank_4_tensor.numpy()))
print("Total numbers of our tensor", tf.size(rank_4_tensor))

In [ ]:
### Indexing tensors, tensors can be index just like python lists
# Get the first 2 elements of each dimension

In [ ]:
# Get the first two elements of each tensor
rank_4_tensor[:2, :2, :2, :2]

In [ ]:
# Get the first element of each dimension from each index except for the final one
rank_4_tensor[:1, :1, :, :1]

In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

In [ ]:
# Get the last item of each of our rank 2 tensor
rank_2_tensor[:, -1]

In [ ]:
# Alter Tensor to meet a certain shape add extra dimension
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

In [ ]:
# Alternative to tf.newaxis to add an extra dimensions
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" expand the final axis

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1)

In [ ]:
### Manipulating Tensors
### You can add values to a tensor using the addition operator this will add 10 to each value
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor + 10


In [ ]:
# Original Tensor is unchanged
tensor

In [ ]:
# Multiplication operation this will multiply 
tensor * 10


In [ ]:
# We can use the tensorflow to substract
tensor - 10

In [ ]:
# We can use the tensorflow built-in function too
# If I want the tensorflow operation sped up best to use to builtin utilities like below
tf.multiply(tensor, 10) # As oppose to tensor * 10

In [ ]:
# Matrix Multiplication in machine learning, matrix multiplication 
# is one of the most common tensor operations
print(tensor)
tf.matmul(tensor, tensor)

In [ ]:
# Practice for 2:31:00 Homework
tensor1 = tf.constant([[1, 2, 5], [7, 2, 1], [3, 3, 3]])
tensor2 = tf.constant([[3, 5], [6, 7], [1, 8]])

In [ ]:
# Matrix multiplication with python "@"
tensor1 @ tensor2

In [ ]:
# For Homework above
tf.matmul(tensor1, tensor2)


In [ ]:
tensor1.shape, tensor2.shape

In [ ]:
# Create a tensor of (3, 2) tensor
tensor4 = tf.constant([[1, 2],
                       [3, 4],
                       [5, 6]])

In [ ]:
tensor5 = tf.constant([[7, 8],
                       [9, 10],
                       [11, 12]])

In [ ]:
tensor4, tensor5

In [ ]:
tf.matmul(tensor4, tensor5)

In [ ]:
# We have two rules our tensors or matricies the inner dimensions must match
# The resulting matrix has the shape of the outer dimensions
# Let's change the shape of tensor5 so the inner dimensions match
tf.reshape(tensor5, shape=(2, 3))

In [ ]:
tensor4.shape, tf.reshape(tensor5, shape=(2, 3)).shape

In [ ]:
# Try to multiple by reshaped tensor5 with Python operator
tensor4 @ tf.reshape(tensor5, shape=(2, 3))

In [ ]:
tf.matmul(tensor4, tf.reshape(tensor5, shape=(2, 3)))

In [ ]:
# The output values depends on what the shape of the tensor is either inner or outer
tf.matmul(tf.reshape(tensor4, shape=(2, 3)), tensor5)

In [ ]:
# Can do the same with transpose, transpose flips the axieses and reshape shuffles the tensors
tf.transpose(tensor4), tf.reshape(tensor4, shape=(2, 3))

In [ ]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(tensor4), tensor5)

In [ ]:
# The dot product
# Matrix multiplication is also refrred to as the dot product
# tf.matmul
# tf.tensordot
tensor4, tensor5

In [ ]:
# Performed the product on tensor4 and tensor5 this requires (tensor4 or tensor5 transposed)
# Transposing is flipping the tensor on the axis
tf.tensordot(tf.transpose(tensor4), tensor5, axes=1)


In [ ]:
# Perform matrix multiplication between tensor4 and tensor5 (transposed)
tf.matmul(tensor4, tf.transpose(tensor5))

In [ ]:
# Perform matrix multiplication between tensor4 and tensor 5 (reshaped)
tf.matmul(tensor4, tf.reshape(tensor5, shape=(2, 3)))

In [ ]:
# Check the values of tensor5, reshape tensor5 and transposed tensor5
print("Normal tensor5:")
print(tensor5, "\n") # "\n" is for newline

print("tensor5 reshaped to (2, 3):")
print(tf.reshape(tensor5, shape=(2, 3)))

print("tensor5 transpose")
print(tf.transpose(tensor5))

In [ ]:
# 2:57 that's (2 hours 57 minutes) into the video is good for debugging
# Generally 
tf.matmul(tensor4, tf.transpose(tensor5))

In [ ]:
#Generally, when performing matrix multiplication on two tensors and one of the axes doesn't 
# line up, you will transpose (rather than reshape) one of tensor to get satisify the matrix
# multiplication rules

In [ ]:
# Change the datatype of a tensor
# Create a new tensor with default datatype (float32)

tensor6 = tf.constant([1.7, 7.4])
tensor6.dtype

In [ ]:
# Change from float 32 to float 16 reduced percision.
# Models run faster with float 16 percision since it's less percisie and uses less memory
tensor7 = tf.cast(tensor6, dtype=tf.float16)

In [ ]:
tensor7

In [ ]:
tensor8 = tf.constant([[7, 10]])
tensor8

In [ ]:
# Casting a tensor from int32 to float32
tensor9 = tf.cast(tensor8, dtype=tf.float32)
tensor9

In [ ]:
# Casting a tensor from int32 to bfloat16
tensor10 = tf.cast(tensor8, dtype=tf.bfloat16)
tensor10

In [ ]:
# Aggregating tensors
# Aggregating tensor = Condensing them for multiple values down to smaller amounts of values
# Get the absolute values
tensor8 = tf.constant([-7, -10])
tf.abs(tensor8)

In [ ]:
# The following the forms of aggregation
# Get the minimum of a tensor
# Get the maximum of a tensor
# Get the mean of a tensor
# Get the sum of a tensor

In [ ]:
# Create a random tensor with values between 0 and 100 of size 50 with numpy random
tensor10 = tf.constant(np.random.randint(0, 100, size=50))
tensor10

In [ ]:
tf.size(tensor10), tensor10.shape, tensor10.ndim

In [ ]:
# Find the lowest value in a tensor
tf.reduce_min(tensor10)

In [ ]:
# Find the highest value in a tensor
tf.reduce_max(tensor10)

In [ ]:
# Find the mean of a tensor
tf.reduce_mean(tensor10)

In [ ]:
# Find the sum of a tensor
tf.reduce_sum(tensor10)

In [ ]:
# Find the variance of the tensor need to install "import tensorflow_probability as tfp"
# Variance is important in investing
tfp.stats.variance(tensor10)

In [ ]:
# Find the variance with with tf.math.reduce_variance(tensor10)
tf.math.reduce_variance(tf.cast(tensor10, dtype=tf.float32))

In [ ]:
# Find the standard deviation of a tensor the number needs to be a float or "real or complex"
# Standard deviation is good for investing
tf.math.reduce_std(tf.cast(tensor10, dtype=tf.float32))

In [ ]:
# Find the positional maximum and minimum what index is the highest value 
# e.g. [100, 99, 98] is that the 0ith index
# e.g. [9, 10, 8] is at the first or 1ith index
# 3:25 into the video
# Can also use tf.random.set_seed(42) for the same output
tensor11 = tf.random.uniform(shape=[50])
tensor11

In [ ]:
# Find the positional maximum
tf.argmax(tensor11)

In [ ]:
# Index on our largest value position the actual number
tensor11[tf.argmax(tensor11)]

In [ ]:
# Find the max value of tensor11
tf.reduce_max(tensor11)

In [ ]:
# Check for equailty, there's assertions in Tensorflow
assert tensor11[tf.argmax(tensor11)] == tf.reduce_max(tensor11)

In [ ]:
# Check for equailty, should equal numpy=True
tensor11[tf.argmax(tensor11)] == tf.reduce_max(tensor11)

In [ ]:
# Finding the positional minimum
tf.argmin(tensor11)

In [ ]:
# Find the minimum using the positional minimum index
tensor11[tf.argmin(tensor11)]

### Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
tensor12 = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
tensor12

In [ ]:
tensor12.shape

In [ ]:
tensor12_squeeze = tf.squeeze(tensor12)
tensor12_squeeze, tensor12_squeeze.shape

# One hot-encoding a form of numerical encoding

In [23]:
# Create a list of indices
some_list = [0, 1, 2, 3, 4] # could be red, green, blue
depth = 3
# one hot encode our list of indices
tf.one_hot(some_list, depth)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [25]:
# specify custom values for one hot encoding
tf.one_hot(some_list, depth=3, on_value="deep learning", 
           off_value="rapping and snapping")

<tf.Tensor: shape=(5, 3), dtype=string, numpy=
array([[b'deep learning', b'rap', b'rap'],
       [b'rap', b'deep learning', b'rap'],
       [b'rap', b'rap', b'deep learning'],
       [b'rap', b'rap', b'rap'],
       [b'rap', b'rap', b'rap']], dtype=object)>

### Squaring, log, square root

In [27]:
# Create a new tensor using the "range" method
tensor13 = tf.range(1, 10)
tensor13

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [29]:
# Square the less tensor Will square every value in the tensor
# e.g. numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9]
# becomes
# numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9]

tf.square(tensor13)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [36]:
# Find the squareroot, need to cast tensor to float first
tensor14 = tf.cast(tensor13, dtype=tf.float16)
tf.sqrt(tensor14)

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [39]:
# Get the log, look this up what's "log"
tf.math.log(tensor14)

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

### Tensors and Numpy

Tensor interacts works will with Numpy arrays.

In [41]:
# Create a tensor directly from a Numpy array
tensor15 = tf.constant(np.array([3., 7., 10.]))
tensor15

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [42]:
# Convert tensor back into a Numpy array
np.array(tensor15), type(np.array(tensor15))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [43]:
# Convert tensor15 to a Numpy array
tensor15.numpy(), type(tensor15.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [46]:
tensor15 = tf.constant([3., 7.])
tensor15.numpy()[1]

7.0

In [47]:
# the default types of each are slighty different
tensor16 = tf.constant(np.array([3., 7., 10.]))
tensor17 = tf.constant([3., 7., 10.])
# Check the datatypes
tensor16.dtype, tensor17.dtype

(tf.float64, tf.float32)